import { ChevronLeft, ChevronRight, Eye, Plus, Search, SlidersHorizontal } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '../../../components/ui/Badge'
import { Button } from '../../../components/ui/Button'
import { EmptyState } from '../../../components/feedback/EmptyState'
import { equipmentSources, equipmentStatuses, equipmentStatusTone, locationLabel, recorded } from '../utils/equipmentDisplay'

function EquipmentSkeleton() { return <div className="equipment-skeleton" aria-label="Loading equipment"><span /><span /><span /><span /><span /></div> }

export function EquipmentList({ equipment, total, isLoading, filters, types, onFilterChange, onPageChange, onNewEquipment }) {
  const pageCount = Math.max(1, Math.ceil(total / filters.pageSize))
  const isEmpty = !isLoading && equipment.length === 0
  return <><div className="list-toolbar equipment-toolbar"><label className="customer-search"><Search size={18} /><input value={filters.search} onChange={(event) => onFilterChange({ search: event.target.value, page: 1 })} placeholder="Search equipment code or serial number" aria-label="Search equipment" /></label><div className="list-toolbar__filters"><label><SlidersHorizontal size={15} /><span className="sr-only">Equipment type</span><select value={filters.equipmentTypeId} onChange={(event) => onFilterChange({ equipmentTypeId: event.target.value, page: 1 })}><option value="">All equipment types</option>{types.map((type) => <option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label><span className="sr-only">Source</span><select value={filters.source} onChange={(event) => onFilterChange({ source: event.target.value, page: 1 })}><option value="">All sources</option>{equipmentSources.map((source) => <option value={source} key={source}>{source}</option>)}</select></label><label><span className="sr-only">Status</span><select value={filters.status} onChange={(event) => onFilterChange({ status: event.target.value, page: 1 })}><option value="">All statuses</option>{equipmentStatuses.map((status) => <option value={status} key={status}>{status}</option>)}</select></label><Button onClick={onNewEquipment}><Plus size={17} />New Equipment</Button></div></div>
    <section className="equipment-table-card"><div className="equipment-table-wrap"><table className="equipment-table"><thead><tr><th>Equipment</th><th>Type / Model</th><th>Customer</th><th>Location</th><th>Source</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{isLoading ? <tr><td colSpan="7"><EquipmentSkeleton /></td></tr> : isEmpty ? <tr><td colSpan="7"><EmptyState icon={SlidersHorizontal} title="No equipment yet" description="No equipment has been recorded yet." action={<Button onClick={onNewEquipment}><Plus size={16} />New Equipment</Button>} /></td></tr> : equipment.map((item) => <tr key={item.id}><td><Link className="customer-table__name" to={`/equipment/${item.id}`}>{item.equipment_code}<small>{item.serial_number || 'Serial not recorded'}</small></Link></td><td><strong>{recorded(item.equipment_types?.name)}</strong><small className="table-subline">{recorded(item.product_models?.model_name)}</small></td><td><Link className="table-view-link" to={`/customers/${item.customer_id}`}>{recorded(item.customers?.name)}</Link><small className="table-subline">{item.customers?.customer_code || ''}</small></td><td>{locationLabel(item.locations)}</td><td>{item.source}</td><td><Badge tone={equipmentStatusTone(item.status)}>{item.status}</Badge></td><td><Link className="table-view-link" to={`/equipment/${item.id}`}><Eye size={16} /><span>View</span></Link></td></tr>)}</tbody></table></div>{!isLoading && total > 0 && <div className="pagination"><span>Showing {(filters.page - 1) * filters.pageSize + 1}–{Math.min(filters.page * filters.pageSize, total)} of {total}</span><div><Button variant="secondary" onClick={() => onPageChange(filters.page - 1)} disabled={filters.page === 1}><ChevronLeft size={17} />Previous</Button><span className="pagination__page">Page {filters.page} of {pageCount}</span><Button variant="secondary" onClick={() => onPageChange(filters.page + 1)} disabled={filters.page >= pageCount}>Next<ChevronRight size={17} /></Button></div></div>}</section>
    <section className="equipment-mobile-list">{isLoading ? <EquipmentSkeleton /> : equipment.map((item) => <article className="equipment-mobile-card" key={item.id}><div><Link to={`/equipment/${item.id}`}><h3>{item.equipment_code}</h3><span>{item.product_models?.model_name || item.equipment_types?.name || 'Equipment details not recorded'}</span></Link><Badge tone={equipmentStatusTone(item.status)}>{item.status}</Badge></div><p><strong>{recorded(item.customers?.name)}</strong><br />{locationLabel(item.locations)}</p><div><span>{item.equipment_types?.name || 'Type not recorded'} · {item.source}</span><Link to={`/equipment/${item.id}`}>View</Link></div></article>)}{isEmpty && <EmptyState icon={SlidersHorizontal} title="No equipment yet" description="No equipment has been recorded yet." action={<Button onClick={onNewEquipment}>New Equipment</Button>} />}</section>
  </>
}

