import { useState } from 'react'
import { Plus, Search } from 'lucide-react'
import { Button } from '../../../components/ui/Button'
import { Card } from '../../../components/ui/Card'
import { Modal } from '../../../components/ui/Modal'
import { Badge } from '../../../components/ui/Badge'
import { masterConfigs, masterErrorMessage } from '../api/masterData'
import { useMasterRows, useSaveMaster, useSetMasterActive, useSettingsLookups } from '../hooks/useSettings'
import { MasterEditor } from './MasterEditor'

export function MasterPanel({ masterKey }) { const config = masterConfigs[masterKey]; const [search, setSearch] = useState(''); const [editor, setEditor] = useState(null); const [notice, setNotice] = useState(''); const rows = useMasterRows(masterKey, search); const lookups = useSettingsLookups(); const save = useSaveMaster(); const active = useSetMasterActive(); const open = (item) => { setNotice(''); setEditor(item ?? {}) }; const submit = async (values) => { try { await save.mutateAsync({ key: masterKey, id: editor?.id, values }); setEditor(null); setNotice('Saved successfully.'); } catch (error) { setNotice(masterErrorMessage(error)) } }; const toggle = async (item) => { const label = item.is_active ? 'Deactivate' : 'Reactivate'; if (item.is_active && !window.confirm(`${label} ${item.name || item.model_name}? It will remain visible in historical records but will not be offered for new selections.`)) return; try { await active.mutateAsync({ key: masterKey, id: item.id, isActive: !item.is_active }); setNotice(`${label}d successfully.`) } catch (error) { setNotice(masterErrorMessage(error)) } }
  return <section className="settings-panel"><header><div><span className="eyebrow">Master data</span><h2>{config.label}</h2><p>{description(masterKey)}</p></div><Button onClick={() => open()}><Plus size={16} />Add {singular(config.label)}</Button></header><div className="settings-toolbar"><label><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder={`Search ${config.label.toLowerCase()}`} /></label></div>{notice && <p className="form-message" role="status">{notice}</p>}<Card className="settings-list">{rows.isLoading ? <p className="settings-state">Loading {config.label.toLowerCase()}…</p> : rows.isError ? <p className="settings-state settings-state--error">This section could not be loaded.</p> : !rows.data?.length ? <p className="settings-state">No records yet.</p> : <div>{rows.data.map((item) => <MasterRow key={item.id} item={item} masterKey={masterKey} working={active.isPending} onEdit={() => open(item)} onToggle={() => toggle(item)} />)}</div>}</Card>{editor && <Modal title={`${editor.id ? 'Edit' : 'Add'} ${singular(config.label)}`} description="Master data is used by future CRM records." onClose={() => setEditor(null)}><MasterEditor masterKey={masterKey} item={editor.id ? editor : null} lookups={lookups.data} saving={save.isPending} onSave={submit} onCancel={() => setEditor(null)} /></Modal>}</section> }
function MasterRow({ item, masterKey, onEdit, onToggle, working }) { const name = item.model_name || item.name; const code = item.product_code || item.part_code || item.technician_code || item.code; return <article className="settings-row"><div><strong>{name}</strong><span>{code && `${code} · `}{summary(item, masterKey)}</span></div><Badge tone={item.is_active ? 'success' : 'neutral'}>{item.is_active ? 'Active' : 'Inactive'}</Badge><div className="settings-row__actions"><Button variant="secondary" onClick={onEdit}>Edit</Button><Button variant="secondary" disabled={working} onClick={onToggle}>{item.is_active ? 'Deactivate' : 'Reactivate'}</Button></div></article> }
function summary(item, key) { if (key === 'productModels') return `${item.equipment_types?.name || 'Equipment type unavailable'} · Default selling price ${item.default_selling_price ?? 'Not set'}`; if (key === 'parts') return `${item.category || 'Uncategorised'}${item.component_roles?.name ? ` · ${item.component_roles.name}` : ''}${item.equipment_tracking_enabled ? ' · Tracked' : ''}${item.part_warranty_eligible ? ' · Warranty eligible' : ''}`; if (key === 'technicians') return [item.phone, item.technician_type].filter(Boolean).join(' · ') || 'No contact details'; return item.description || 'Operational master record' }
function singular(label) { return label.endsWith('s') ? label.slice(0, -1) : label }
function description(key) { if (key === 'productModels') return 'Default selling price and cost only; historical sale prices remain unchanged.'; if (key === 'parts') return 'Configure defaults, warranty eligibility and component tracking from the stored flags.'; if (key === 'technicians') return 'Inactive technicians remain visible in historical visits but are excluded from new assignments.'; if (key === 'paymentMethods') return 'Financial history is preserved; deactivate methods instead of deleting them.'; return 'Manage operational configuration for future CRM records.' }

