import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { Button } from '../../../components/ui/Button'
import { masterConfigs } from '../api/masterData'

const blank = { is_active: true, name: '', model_name: '', equipment_type_id: '', description: '', default_selling_price: '', default_cost: '', notes: '', category: '', brand: '', model: '', component_role_id: '', standard_cost: '', standard_selling_price: '', equipment_tracking_enabled: false, part_warranty_eligible: false, default_warranty_months: '', phone: '', technician_type: '' }
const title = (key, item) => item ? `Edit ${masterConfigs[key].label.slice(0, -1)}` : `Add ${masterConfigs[key].label.slice(0, -1)}`

export function MasterEditor({ masterKey, item, lookups, saving, onSave, onCancel }) {
  const { register, handleSubmit, watch, setValue, formState: { errors } } = useForm({ values: { ...blank, ...item, component_role_id: item?.component_role_id ?? '', equipment_type_id: item?.equipment_type_id ?? '' } })
  const tracking = watch('equipment_tracking_enabled'); const warranty = watch('part_warranty_eligible')
  useEffect(() => { if (!warranty) setValue('default_warranty_months', '') }, [warranty, setValue])
  const fields = masterKey === 'productModels' ? <ProductFields register={register} errors={errors} lookups={lookups} /> : masterKey === 'parts' ? <PartFields register={register} errors={errors} lookups={lookups} tracking={tracking} warranty={warranty} /> : masterKey === 'technicians' ? <TechnicianFields register={register} errors={errors} /> : masterKey === 'equipmentTypes' ? <><NameField register={register} errors={errors} /><TextArea label="Description" register={register} name="description" /></> : <NameField register={register} errors={errors} />
  return <form className="settings-form" onSubmit={handleSubmit(onSave)}><h3>{title(masterKey, item)}</h3><p>Changes affect future selections. Historical records keep their existing references.</p><div className="settings-form__grid">{fields}</div><label className="settings-check"><input type="checkbox" {...register('is_active')} /> Active and available for new CRM records</label><div className="settings-form__actions"><Button type="button" variant="secondary" onClick={onCancel}>Cancel</Button><Button type="submit" disabled={saving}>{saving ? 'Saving…' : 'Save changes'}</Button></div></form>
}
function NameField({ register, errors, label = 'Name' }) { return <label>{label}<input autoFocus {...register('name', { required: `${label} is required.` })} />{errors.name && <small>{errors.name.message}</small>}</label> }
function TextArea({ label, register, name }) { return <label>{label}<textarea {...register(name)} /></label> }
function NumberField({ label, register, name, required = false }) { return <label>{label}<input type="number" min="0" step="0.01" {...register(name, { required: required ? `${label} is required.` : false, min: { value: 0, message: 'Use a nonnegative amount.' } })} /></label> }
function ProductFields({ register, errors, lookups }) { return <><label>Model name<input autoFocus {...register('model_name', { required: 'Model name is required.' })} />{errors.model_name && <small>{errors.model_name.message}</small>}</label><label>Equipment type<select {...register('equipment_type_id', { required: 'Choose an equipment type.' })}><option value="">Choose type</option>{(lookups?.equipmentTypes ?? []).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select>{errors.equipment_type_id && <small>{errors.equipment_type_id.message}</small>}</label><NumberField label="Default Selling Price" register={register} name="default_selling_price" /><NumberField label="Default Cost" register={register} name="default_cost" /><TextArea label="Description" register={register} name="description" /><TextArea label="Notes" register={register} name="notes" /></> }
function PartFields({ register, errors, lookups, tracking, warranty }) { return <><NameField register={register} errors={errors} /><label>Category<input {...register('category')} /></label><label>Brand<input {...register('brand')} /></label><label>Model<input {...register('model')} /></label><NumberField label="Standard Cost" register={register} name="standard_cost" /><NumberField label="Standard Selling Price" register={register} name="standard_selling_price" /><label>Component role<select {...register('component_role_id', { validate: (value) => !tracking || !!value || 'Tracked parts require a component role.' })}><option value="">Not configured</option>{(lookups?.componentRoles ?? []).map((row) => <option key={row.id} value={row.id}>{row.name}</option>)}</select>{errors.component_role_id && <small>{errors.component_role_id.message}</small>}</label><label className="settings-check"><input type="checkbox" {...register('equipment_tracking_enabled')} /> Equipment tracking enabled</label><label className="settings-check"><input type="checkbox" {...register('part_warranty_eligible')} /> Part warranty eligible</label><label>Default warranty months<input type="number" min="1" step="1" disabled={!warranty} {...register('default_warranty_months', { min: { value: 1, message: 'Warranty duration must be at least one month.' } })} /></label><TextArea label="Notes" register={register} name="notes" /></> }
function TechnicianFields({ register, errors }) { return <><NameField register={register} errors={errors} /><label>Phone<input inputMode="tel" {...register('phone')} /></label><label>Technician type<input {...register('technician_type')} /></label><TextArea label="Notes" register={register} name="notes" /></> }

