import { Plus, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Button } from '../components/ui/Button'
import { CoverageDirectory } from '../features/coverage/components/CoverageDirectory'
import { useAmcCycles, useEquipmentWarranties, usePartWarranties } from '../features/coverage/hooks/useCoverage'

const tabs = [{ id: 'warranties', label: 'Equipment Warranties' }, { id: 'amc', label: 'AMC' }, { id: 'parts', label: 'Part Warranties' }]
const statuses = ['', 'Active', 'Expired', 'Cancelled', 'Void', 'Unknown']
export function CoveragePage() { const [tab, setTab] = useState('warranties'); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [status, setStatus] = useState(''); const [fromDate, setFromDate] = useState(''); const [toDate, setToDate] = useState(''); const filters = { page, pageSize: 25, search, status, fromDate, toDate }; const warranties = useEquipmentWarranties(filters); const amcs = useAmcCycles(filters); const parts = usePartWarranties(filters); const active = tab==='warranties'?warranties:tab==='amc'?amcs:parts; function changeTab(next) { setTab(next); setPage(1); setSearch(''); setStatus('') } function resetPage(update) { update(); setPage(1) } return <div className="coverage-page"><header className="page-heading"><div><span className="eyebrow">Coverage</span><h2>Coverage workspace</h2><p>Equipment warranties, AMC cycles and service-created part warranties.</p></div>{tab==='amc' && <Link to="/coverage/amc/new"><Button><Plus size={17} />New AMC</Button></Link>}</header><div className="coverage-tabs" role="tablist">{tabs.map((item) => <button key={item.id} type="button" role="tab" aria-selected={tab===item.id} className={tab===item.id?'active':''} onClick={() => changeTab(item.id)}>{item.label}</button>)}</div><div className="coverage-toolbar"><label>Search<input value={search} onChange={(event) => resetPage(() => setSearch(event.target.value))} placeholder={tab==='amc'?'Search AMC code':tab==='parts'?'Search part warranty code':'Search warranty code'} /></label><label>Status<select value={status} onChange={(event) => resetPage(() => setStatus(event.target.value))}>{statuses.map((item) => <option value={item} key={item || 'all'}>{item || 'All statuses'}</option>)}</select></label>{tab!=='parts' && <><label>From<input type="date" value={fromDate} onChange={(event) => resetPage(() => setFromDate(event.target.value))} /></label><label>To<input type="date" value={toDate} onChange={(event) => resetPage(() => setToDate(event.target.value))} /></label></>}</div>{tab==='warranties' && <CoverageDirectory kind="warranty" {...(warranties.data ?? { rows: [], count: 0 })} page={page} onPage={setPage} isLoading={warranties.isLoading} emptyTitle="No equipment warranties have been activated yet." emptyDescription="Warranty activation begins from completed Installation, which is not part of this phase." />}{tab==='amc' && <CoverageDirectory kind="amc" {...(amcs.data ?? { rows: [], count: 0 })} page={page} onPage={setPage} isLoading={amcs.isLoading} emptyTitle="No AMC cycles have been recorded." emptyDescription="Create an AMC for existing equipment using the guided workflow." />}{tab==='parts' && <CoverageDirectory kind="part" {...(parts.data ?? { rows: [], count: 0 })} page={page} onPage={setPage} isLoading={parts.isLoading} emptyTitle="No part warranties have been issued." emptyDescription="Part warranties are created only by completed Service workflows." />}</div> }

