import { ArrowLeft } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { ErrorState } from '../components/feedback/ErrorState'
import { Badge } from '../components/ui/Badge'
import { Card } from '../components/ui/Card'
import { useEquipmentWarranty } from '../features/coverage/hooks/useCoverage'
import { date, equipmentLabel, money, statusTone } from '../features/coverage/utils/coverageDisplay'
export function EquipmentWarrantyDetailPage() { const { warrantyId }=useParams(); const query=useEquipmentWarranty(warrantyId); if(query.isLoading)return <p className="detail-loading">Loading warranty…</p>; if(query.isError||!query.data)return <ErrorState title="Warranty could not be loaded" description="The warranty may be unavailable or you may not have access."/>; const w=query.data; return <div className="coverage-detail"><Link className="back-link" to="/coverage"><ArrowLeft size={17}/>Coverage</Link><header className="customer-detail__header"><div><span className="eyebrow">Equipment warranty</span><h2>{w.warranty_code}</h2><p>{equipmentLabel(w.equipment)} · {w.equipment?.customers?.name}</p></div><Badge tone={statusTone(w.status)}>{w.status}</Badge></header><div className="coverage-detail__grid"><Card><h2>Overview</h2><p className="coverage-detail-item"><strong>Equipment</strong><Link to={`/equipment/${w.equipment_id}`}>{equipmentLabel(w.equipment)}</Link></p><p className="coverage-detail-item"><strong>Customer</strong><Link to={`/customers/${w.equipment?.customer_id}`}>{w.equipment?.customers?.name}</Link></p><p className="coverage-detail-item"><strong>Product model</strong><span>{w.equipment?.product_models?.model_name??'Not recorded'}</span></p><p className="coverage-detail-item"><strong>Dates</strong><span>{date(w.start_date)} to {date(w.end_date)}</span></p><p className="coverage-detail-item"><strong>Duration / planned visits</strong><span>{w.duration_months} months · {w.planned_visits} planned</span></p><p className="coverage-detail-item"><strong>Sale / installation</strong><span>{w.sales?.sale_code??'Not traceable'} · {w.installations?.installation_code??'Not traceable'}</span></p><p className="coverage-detail-item"><strong>Notes</strong><span>{w.notes||'Not recorded'}</span></p></Card><Card><h2>Warranty service history</h2>{w.services?.length?w.services.map((service)=><Link className="coverage-linked-row" key={service.id} to={`/service/${service.id}`}><strong>{service.service_code}</strong><span>{date(service.service_date)} · {service.service_types?.name??'Service'} · {money(service.technician_charge)} · {service.status}</span></Link>):<p className="coverage-empty-copy">No service visits have used this warranty.</p>}</Card></div></div> }

