import { ArrowDown, ArrowLeft } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { ErrorState } from '../components/feedback/ErrorState'
import { Badge } from '../components/ui/Badge'
import { Card } from '../components/ui/Card'
import { usePartWarranty } from '../features/coverage/hooks/useCoverage'
import { date, equipmentLabel, statusTone } from '../features/coverage/utils/coverageDisplay'
export function PartWarrantyDetailPage() { const { partWarrantyId }=useParams(); const query=usePartWarranty(partWarrantyId); if(query.isLoading)return <p className="detail-loading">Loading part warranty…</p>; if(query.isError||!query.data)return <ErrorState title="Part warranty could not be loaded" description="The warranty may be unavailable or you may not have access."/>; const { warranty:w,chain }=query.data; return <div className="coverage-detail"><Link className="back-link" to="/coverage"><ArrowLeft size={17}/>Coverage</Link><header className="customer-detail__header"><div><span className="eyebrow">Part warranty</span><h2>{w.part_warranty_code}</h2><p>{w.parts?.name} · {equipmentLabel(w.equipment)} · {w.equipment?.customers?.name}</p></div><Badge tone={statusTone(w.status)}>{w.status}</Badge></header><div className="coverage-detail__grid"><Card><h2>Overview</h2><p className="coverage-detail-item"><strong>Equipment</strong><Link to={`/equipment/${w.equipment_id}`}>{equipmentLabel(w.equipment)}</Link></p><p className="coverage-detail-item"><strong>Part</strong><span>{w.parts?.name??'Unavailable'}</span></p><p className="coverage-detail-item"><strong>Dates</strong><span>{date(w.start_date)} to {date(w.end_date)} · {w.duration_months} months</span></p><p className="coverage-detail-item"><strong>Source service</strong>{w.service_items?.services?<Link to={`/service/${w.service_items.services.id}`}>{w.service_items.services.service_code}</Link>:<span>Not traceable</span>}</p><p className="coverage-detail-item"><strong>Notes</strong><span>{w.notes||'Not recorded'}</span></p></Card><Card><h2>Replacement chain</h2><p className="coverage-empty-copy">Stored replacement links only; no relationships are inferred.</p><div className="coverage-chain">{chain.map((item,index)=><div key={item.id}>{index>0&&<ArrowDown size={19}/>}<Link className={item.id===w.id?'coverage-chain__current':'coverage-chain__item'} to={`/coverage/part-warranties/${item.id}`}><strong>{item.part_warranty_code}</strong><span>{item.parts?.name} · {date(item.start_date)} to {date(item.end_date)} · {item.status}</span>{item.service_items?.services&&<small>Replacement service: {item.service_items.services.service_code}</small>}</Link></div>)}</div></Card></div></div> }

