import { Plus, Trash2 } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { useForm } from 'react-hook-form'
import { Button } from '../../../components/ui/Button'
import { useSaleCustomerLocations, useSaleCustomerSearch, useSaleLookups } from '../hooks/useSales'
import { formatCurrency, saleErrorMessage } from '../utils/salesDisplay'

const blankLine = () => ({ id: crypto.randomUUID(), product_model_id: '', quantity: 1, standard_unit_price: '', actual_unit_price: '', unit_cost: '', discount: 0, warranty_months: 12, notes: '', unit_locations: [''] })
const today = () => new Date().toLocaleDateString('en-CA')

export function NewSaleForm({ initialCustomer, onSubmit, isSubmitting }) {
  const { register, handleSubmit, watch, setValue } = useForm({ defaultValues: { saleDate: today(), status: 'Confirmed', invoiceNumber: '', invoiceDate: '', leadSourceId: '', sourceDetail: '', notes: '' } })
  const lookupQuery = useSaleLookups()
  const [customer, setCustomer] = useState(initialCustomer || null)
  const [customerTerm, setCustomerTerm] = useState(initialCustomer?.name || '')
  const customerQuery = useSaleCustomerSearch(customerTerm)
  const locationsQuery = useSaleCustomerLocations(customer?.id)
  const [lines, setLines] = useState([blankLine()])
  const [step, setStep] = useState(1)
  const [error, setError] = useState('')
  const submissionKey = useRef(crypto.randomUUID())
  useEffect(() => { if (initialCustomer?.id) { setCustomer(initialCustomer); setCustomerTerm(initialCustomer.name) } }, [initialCustomer])
  const products = lookupQuery.data?.products ?? []
  const locations = locationsQuery.data ?? []
  const updateLine = (id, change) => setLines((current) => current.map((line) => line.id === id ? { ...line, ...change } : line))
  const chooseProduct = (line, productId) => { const product = products.find((candidate) => candidate.id === productId); updateLine(line.id, { product_model_id: productId, standard_unit_price: product?.default_selling_price ?? '', actual_unit_price: product?.default_selling_price ?? '', unit_cost: product?.default_cost ?? '' }) }
  const setQuantity = (line, raw) => { const quantity = Math.max(1, Number(raw) || 1); updateLine(line.id, { quantity, unit_locations: Array.from({ length: quantity }, (_, index) => line.unit_locations[index] || '') }) }
  const chooseCustomer = (next) => { setCustomer(next); setCustomerTerm(next.name); setLines((current) => current.map((line) => ({ ...line, unit_locations: Array.from({ length: line.quantity }, () => '') }))) }
  const lineTotal = (line) => Number(line.actual_unit_price || 0) * Number(line.quantity || 0)
  const valid = customer && lines.length && lines.every((line) => line.product_model_id && Number(line.quantity) > 0 && line.actual_unit_price !== '')
  async function submit(values) { setError(''); if (!valid) { setError('Choose a customer and complete every product line.'); return } try { await onSubmit({ ...values, customerId: customer.id, items: lines, submissionKey: submissionKey.current }); submissionKey.current = crypto.randomUUID() } catch (submitError) { setError(saleErrorMessage(submitError)) } }
  return <form className="sale-wizard" onSubmit={handleSubmit(submit)}>
    <ol className="sale-wizard__steps"><li className={step >= 1 ? 'active' : ''}>1. Customer</li><li className={step >= 2 ? 'active' : ''}>2. Products & locations</li><li className={step >= 3 ? 'active' : ''}>3. Pricing & warranty</li><li className={step >= 4 ? 'active' : ''}>4. Review</li></ol>
    {error && <p className="form-message" role="alert">{error}</p>}
    {step === 1 && <section className="sale-wizard__panel"><h3>Choose customer</h3><p>Search by customer name, phone, or customer ID.</p><label className="form-field">Customer search<input value={customerTerm} onChange={(event) => { setCustomerTerm(event.target.value); if (customer) setCustomer(null) }} placeholder="Start typing…" /></label>{!customer && customerTerm.length > 1 && <div className="customer-combobox__results">{customerQuery.isLoading && <span>Searching…</span>}{(customerQuery.data ?? []).map((result) => <button type="button" key={result.id} onClick={() => chooseCustomer(result)}><strong>{result.name}</strong><small>{result.customer_code} · {result.phone || 'Phone not recorded'}</small></button>)}</div>}{customer && <p className="sale-selected-customer"><strong>{customer.name}</strong><span>{customer.customer_code} · {customer.phone || 'Phone not recorded'}</span></p>}</section>}
    {step === 2 && <section className="sale-wizard__panel"><h3>Products & physical units</h3><p>Every unit receives its own active customer-location assignment.</p>{lines.map((line, index) => <article className="sale-line" key={line.id}><div className="sale-line__top"><strong>Product line {index + 1}</strong>{lines.length > 1 && <button type="button" className="text-button" onClick={() => setLines((current) => current.filter((candidate) => candidate.id !== line.id))}><Trash2 size={15} />Remove</button>}</div><label>Product<select value={line.product_model_id} onChange={(event) => chooseProduct(line, event.target.value)}><option value="">Choose active product…</option>{products.map((product) => <option key={product.id} value={product.id}>{product.model_name} ({product.product_code})</option>)}</select></label><label>Quantity<input min="1" type="number" value={line.quantity} onChange={(event) => setQuantity(line, event.target.value)} /></label>{Array.from({ length: line.quantity }, (_, unitIndex) => <label key={unitIndex}>Unit {unitIndex + 1} location<select value={line.unit_locations[unitIndex] || ''} onChange={(event) => updateLine(line.id, { unit_locations: line.unit_locations.map((value, index2) => index2 === unitIndex ? event.target.value : value) })}><option value="">Not assigned</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.location_name || [location.area, location.city].filter(Boolean).join(', ') || location.location_code}</option>)}</select></label>)}</article>)}<Button type="button" variant="secondary" onClick={() => setLines((current) => [...current, blankLine()])}><Plus size={16} />Add product line</Button></section>}
    {step === 3 && <section className="sale-wizard__panel"><h3>Pricing & warranty</h3><p>Warranty begins from completed installation.</p>{lines.map((line, index) => <article className="sale-line sale-line--pricing" key={line.id}><strong>Line {index + 1}</strong><div className="sale-line__grid"><label>Standard price<input type="number" min="0" value={line.standard_unit_price} onChange={(event) => updateLine(line.id, { standard_unit_price: event.target.value })} /></label><label>Actual price<input type="number" min="0" required value={line.actual_unit_price} onChange={(event) => updateLine(line.id, { actual_unit_price: event.target.value })} /></label><label>Cost snapshot<input type="number" min="0" value={line.unit_cost} onChange={(event) => updateLine(line.id, { unit_cost: event.target.value })} /></label><label>Discount (informational)<input type="number" min="0" value={line.discount} onChange={(event) => updateLine(line.id, { discount: event.target.value })} /></label><label>Warranty<select value={line.warranty_months} onChange={(event) => updateLine(line.id, { warranty_months: Number(event.target.value) })}><option value="0">No warranty</option><option value="12">12 months</option><option value="24">24 months</option></select></label><label>Notes<input value={line.notes} onChange={(event) => updateLine(line.id, { notes: event.target.value })} /></label></div><p className="sale-line__total">Line total: {formatCurrency(lineTotal(line))}</p></article>)}</section>}
    {step === 4 && <section className="sale-wizard__panel"><h3>Review sale</h3><label>Sale date<input type="date" {...register('saleDate', { required: true })} /></label><label>Status<select {...register('status')}><option>Confirmed</option><option>Draft</option></select></label><label>Invoice number<input {...register('invoiceNumber')} /></label><label>Invoice date<input type="date" {...register('invoiceDate')} /></label><label>Lead source<select {...register('leadSourceId')}><option value="">Not recorded</option>{(lookupQuery.data?.leadSources ?? []).map((source) => <option key={source.id} value={source.id}>{source.name}</option>)}</select></label><label>Source detail<input {...register('sourceDetail')} /></label><label>Notes<textarea {...register('notes')} /></label><div className="sale-review-total"><span>Sale total</span><strong>{formatCurrency(lines.reduce((sum, line) => sum + lineTotal(line), 0))}</strong></div></section>}
    <div className="sale-wizard__actions">{step > 1 && <Button type="button" variant="secondary" onClick={() => setStep((current) => current - 1)}>Back</Button>}{step < 4 ? <Button type="button" onClick={() => { if (step === 1 && !customer) setError('Choose a customer before continuing.'); else setStep((current) => current + 1) }}>Continue</Button> : <Button type="submit" disabled={isSubmitting || !valid}>{isSubmitting ? 'Creating sale…' : 'Create sale'}</Button>}</div>
  </form>
}

