import { supabase } from '../../../lib/supabase'
const client=()=>{if(!supabase)throw new Error('Supabase is not configured.');return supabase};const nil=value=>typeof value==='string'?value.trim()||null:value??null;const num=value=>value===''||value===null||value===undefined?null:Number(value)
export async function createAtomicService(values){const rpcName=values.destinationLocationId?'create_service_with_items_v2_relocation':'create_service_with_items_v2';const{data,error}=await client().rpc(rpcName,{p_submission_key:values.submissionKey,p_equipment_id:values.equipmentId,p_service_date:values.serviceDate,p_service_type_id:values.serviceTypeId,p_status:values.status,p_destination_location_id:values.destinationLocationId||undefined,p_items:values.items.map(item=>({part_id:item.part_id||null,item_type:item.item_type,description:nil(item.description),quantity:Number(item.quantity),standard_price:num(item.standard_price),actual_customer_price:0,internal_cost:Number(item.internal_cost||0),coverage_type:item.coverage_type,equipment_warranty_id:item.equipment_warranty_id||null,amc_cycle_id:item.amc_cycle_id||null,service_item_warranty_id:item.service_item_warranty_id||null,updates_equipment_component:Boolean(item.updates_equipment_component),notes:nil(item.notes),issue_new_part_warranty:Boolean(item.issue_new_part_warranty)})),p_final_customer_charge:num(values.finalCustomerCharge),p_travel_cost:num(values.travelCost)??0,p_other_direct_cost:num(values.otherDirectCost)??0,p_other_direct_cost_note:nil(values.otherDirectCostNote),p_customer_charge_note:nil(values.customerChargeNote),p_technician_id:values.technicianId||null,p_issue_reported:nil(values.issueReported),p_diagnosis:nil(values.diagnosis),p_work_performed:nil(values.workPerformed),p_tds_in:num(values.tdsIn),p_tds_out:num(values.tdsOut),p_next_service_due:values.nextServiceDue||null,p_technician_charge:num(values.technicianCharge)??0,p_equipment_warranty_id:values.equipmentWarrantyId||null,p_amc_cycle_id:values.amcCycleId||null,p_notes:nil(values.notes)});if(error)throw error;const serviceId=data?.[0]?.service_id;if(!serviceId)throw new Error('The service was created but no reference was returned.');return{serviceId,rows:data??[]}}
export async function addServicePayment({serviceId,values}){const{data,error}=await client().from('service_payments').insert({service_id:serviceId,payment_date:values.payment_date,amount:Number(values.amount),payment_method_id:values.payment_method_id,reference_number:nil(values.reference_number),notes:nil(values.notes)}).select().single();if(error)throw error;return data}


export async function correctService({ serviceId, values }) { const { data, error } = await client().rpc('correct_service', { p_service_id: serviceId, p_service_date: values.service_date, p_technician_id: values.technician_id || null, p_next_service_due: values.next_service_due || null, p_notes: nil(values.notes), p_final_customer_charge: num(values.final_customer_charge), p_technician_charge: num(values.technician_charge) ?? 0, p_travel_cost: num(values.travel_cost) ?? 0, p_other_direct_cost: num(values.other_direct_cost) ?? 0, p_other_direct_cost_note: nil(values.other_direct_cost_note), p_customer_charge_note: nil(values.customer_charge_note), p_items: values.items.map((item) => ({ id: item.id, standard_price: num(item.standard_price), actual_customer_price: num(item.actual_customer_price) ?? 0, internal_cost: num(item.internal_cost) ?? 0 })), p_correction_note: nil(values.correction_note) }); if (error) throw error; return data }

export async function amendService({ serviceId, values }) {
  const header = { service_date: values.service_date, technician_id: values.technician_id || null, issue_reported: nil(values.issue_reported), diagnosis: nil(values.diagnosis), work_performed: nil(values.work_performed), tds_in: num(values.tds_in), tds_out: num(values.tds_out), next_service_due: values.next_service_due || null, notes: nil(values.notes), final_customer_charge: num(values.final_customer_charge), technician_charge: num(values.technician_charge) ?? 0, travel_cost: num(values.travel_cost) ?? 0, other_direct_cost: num(values.other_direct_cost) ?? 0, other_direct_cost_note: nil(values.other_direct_cost_note), customer_charge_note: nil(values.customer_charge_note) }
  const items = values.items.map((item) => ({ id: item.id || undefined, action: item.action, part_id: item.part_id || null, item_type: item.item_type, description: nil(item.description), quantity: Number(item.quantity), standard_price: num(item.standard_price), actual_customer_price: num(item.actual_customer_price) ?? 0, internal_cost: num(item.internal_cost) ?? 0, coverage_type: item.coverage_type, equipment_warranty_id: item.equipment_warranty_id || null, amc_cycle_id: item.amc_cycle_id || null, service_item_warranty_id: item.service_item_warranty_id || null, updates_equipment_component: Boolean(item.updates_equipment_component), issue_new_part_warranty: Boolean(item.issue_new_part_warranty), notes: nil(item.notes) }))
  const { data, error } = await client().rpc('amend_service', { p_service_id: serviceId, p_header: header, p_items: items, p_correction_note: nil(values.correction_note) })
  if (error) throw error
  return data
}