import { supabase } from '../../../lib/supabase'
import { serviceTotals } from './serviceQueries'
const client=()=>{if(!supabase)throw new Error('Supabase is not configured.');return supabase};const safe=(term)=>term.trim().replace(/[%,_(),]/g,' ')
export async function searchServiceEquipment(search){const term=safe(search);if(term.length<2)return[];const{data,error}=await client().from('equipment').select('id, equipment_code, serial_number, status, customer_id, location_id, customers ( id, customer_code, name, phone ), locations ( id, location_name, area, city, pincode ), equipment_types ( name ), product_models ( model_name )').or(`equipment_code.ilike.%${term}%,serial_number.ilike.%${term}%`).limit(10);if(error)throw error;return data??[]}
export async function getServiceCustomerLocations(customerId){if(!customerId)return[];const{data,error}=await client().from('locations').select('id, location_name, area, city, pincode').eq('customer_id',customerId).eq('is_active',true).order('created_at');if(error)throw error;return data??[]}
export async function getEquipmentCoverage(equipmentId,serviceDate){if(!equipmentId||!serviceDate)return{warranties:[],amcCycles:[]};const[warranties,amcCycles]=await Promise.all([client().from('equipment_warranties').select('id, warranty_code, start_date, end_date, duration_months').eq('equipment_id',equipmentId).eq('status','Active').lte('start_date',serviceDate).gte('end_date',serviceDate).order('end_date'),client().from('amc_cycles').select('id, amc_code, cycle_number, start_date, end_date, planned_visits').eq('equipment_id',equipmentId).eq('status','Active').lte('start_date',serviceDate).gte('end_date',serviceDate).order('end_date')]);if(warranties.error||amcCycles.error)throw warranties.error||amcCycles.error;return{warranties:warranties.data??[],amcCycles:amcCycles.data??[]}}
export async function getPartWarranties(equipmentId,partId,serviceDate){if(!equipmentId||!partId||!serviceDate)return[];const{data,error}=await client().from('service_item_warranties').select('id, part_warranty_code, start_date, end_date, duration_months').eq('equipment_id',equipmentId).eq('part_id',partId).eq('status','Active').lte('start_date',serviceDate).gte('end_date',serviceDate).order('end_date');if(error)throw error;return data??[]}
export async function getEquipmentServices(equipmentId){const{data,error}=await client().from('services').select('id, service_code, service_date, status, service_type_id, financial_model_version, final_customer_charge, service_types ( name ), service_items ( id, quantity, actual_customer_price ), service_payments ( id, amount )').eq('equipment_id',equipmentId).order('service_date',{ascending:false}).order('created_at',{ascending:false}).limit(10);if(error)throw error;return(data??[]).map(service=>({...service,totals:serviceTotals(service)}))}

