import { ChevronLeft, ChevronRight, Eye, Plus, Search, SlidersHorizontal, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Badge } from '../../../components/ui/Badge'
import { Button } from '../../../components/ui/Button'
import { EmptyState } from '../../../components/feedback/EmptyState'
import { displayLocation, customerStatus } from '../utils/customerDisplay'

function CustomerSkeleton() {
  return <div className="customer-skeleton" aria-label="Loading customers"><span /><span /><span /><span /><span /></div>
}

export function CustomerList({ customers, isLoading, filters, onFilterChange, total, onPageChange, onNewCustomer }) {
  const pageCount = Math.max(1, Math.ceil(total / filters.pageSize))
  return <><div className="list-toolbar"><label className="customer-search"><Search size={18} /><input value={filters.search} onChange={(event) => onFilterChange({ search: event.target.value, page: 1 })} placeholder="Search by name, phone, customer ID, area, city or pincode" aria-label="Search customers" /></label><div className="list-toolbar__filters"><label><SlidersHorizontal size={15} /><span className="sr-only">Customer type</span><select value={filters.customerTypeId} onChange={(event) => onFilterChange({ customerTypeId: event.target.value, page: 1 })}><option value="">All customer types</option>{filters.customerTypes.map((type) => <option value={type.id} key={type.id}>{type.name}</option>)}</select></label><label><span className="sr-only">Customer status</span><select value={filters.status} onChange={(event) => onFilterChange({ status: event.target.value, page: 1 })}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select></label><label><span className="sr-only">City</span><select value={filters.city} onChange={(event) => onFilterChange({ city: event.target.value, page: 1 })} disabled={filters.locationFiltersLoading}><option value="">All cities</option>{filters.cities.map((city) => <option value={city} key={city}>{city}</option>)}</select></label><label><span className="sr-only">Area</span><select value={filters.area} onChange={(event) => onFilterChange({ area: event.target.value, page: 1 })} disabled={filters.locationFiltersLoading}><option value="">All areas</option>{filters.areas.map((area) => <option value={area} key={area}>{area}</option>)}</select></label><Button onClick={onNewCustomer}><Plus size={17} />New Customer</Button></div></div>
    <section className="customer-table-card"><div className="customer-table-wrap"><table className="customer-table"><thead><tr><th>Customer</th><th>Phone</th><th>Type</th><th>Area</th><th>Status</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{isLoading ? <tr><td colSpan="6"><CustomerSkeleton /></td></tr> : customers.length === 0 ? <tr><td colSpan="6"><EmptyState icon={UsersRound} title="No customers yet" description="Create your first customer to begin building the CRM." action={<Button onClick={onNewCustomer}><Plus size={16} />New Customer</Button>} /></td></tr> : customers.map((customer) => <tr key={customer.id}><td><Link className="customer-table__name" to={`/customers/${customer.id}`}>{customer.name}<small>{customer.customer_code}</small></Link></td><td>{customer.phone || 'Not recorded'}</td><td>{customer.customer_types?.name || 'Not recorded'}</td><td>{displayLocation(customer.representativeLocation)}</td><td><Badge tone={customer.is_active ? 'success' : 'neutral'}>{customerStatus(customer)}</Badge></td><td><Link className="table-view-link" to={`/customers/${customer.id}`}><Eye size={16} /><span>View</span></Link></td></tr>)}</tbody></table></div>
      {!isLoading && total > 0 && <div className="pagination"><span>Showing {(filters.page - 1) * filters.pageSize + 1}–{Math.min(filters.page * filters.pageSize, total)} of {total}</span><div><Button variant="secondary" onClick={() => onPageChange(filters.page - 1)} disabled={filters.page === 1}><ChevronLeft size={17} />Previous</Button><span className="pagination__page">Page {filters.page} of {pageCount}</span><Button variant="secondary" onClick={() => onPageChange(filters.page + 1)} disabled={filters.page >= pageCount}>Next<ChevronRight size={17} /></Button></div></div>}</section>
    <section className="customer-mobile-list">{isLoading ? <CustomerSkeleton /> : customers.map((customer) => <article className="customer-mobile-card" key={customer.id}><div><Link to={`/customers/${customer.id}`}><h3>{customer.name}</h3><span>{customer.customer_code}</span></Link><Badge tone={customer.is_active ? 'success' : 'neutral'}>{customerStatus(customer)}</Badge></div><p>{customer.phone || 'Phone not recorded'}</p><p>{displayLocation(customer.representativeLocation)}</p><div><span>{customer.customer_types?.name || 'Type not recorded'}</span><Link to={`/customers/${customer.id}`}>View</Link></div></article>)}{!isLoading && customers.length === 0 && <EmptyState icon={UsersRound} title="No customers yet" description="Create your first customer to begin building the CRM." action={<Button onClick={onNewCustomer}>New Customer</Button>} />}</section>
  </>
}

